- contxt/auth/__init__.py
- contxt/models/events.py
- contxt/services/api.py
- contxt/services/assets.py
- contxt/services/events.py
- contxt/utils/__init__.py
- tests/services/test_auth.py
Please, don't merge yet. The purpose is to start a discussion on how to fix these issues:
- token renewal should be handled automatically
- http request sessions should be aware of token expirations
> DO NOT MERGE: hot fixes required by novo api

- contxt/cli/parsers.py
> Fix org print output

- contxt/models/iot.py
- contxt/services/iot.py
- contxt/utils/serializer.py
* Creating an Iot Field was not supported
* Add `create_field` method
> Add method to create field

- contxt/services/contxt.py
* Contxt API had incorrect client id
> Fix contxt client id

- contxt/models/contxt.py
* [https://ndustrialio.atlassian.net/browse/NC2-1202](https://ndustrialio.atlassian.net/browse/NC2-1202): I need the slug to link in the email
- Exposed the slug so that I can link to nSight
> Exposing slug on organizations

- contxt/services/events.py
It had the input of Event, but it should be EventType
Changed the input type
> Applying proper event type input parameter

- .github/workflows/ci.yaml
> fix: setup python before publishing

- .github/workflows/ci.yaml
- contxt/cli/commands/ems.py
- contxt/cli/commands/iot.py
- contxt/models/etl.py
- contxt/services/assets.py
- contxt/utils/decorators.py
- contxt/utils/serializer.py
- poetry.lock
- pyproject.toml
- tests/auth/test_base.py
* Really just trying to push a new release, but our windows test runner was stuck even after 30 min...
* Update latest deps
* Slim down ci matrix
> build: update deps

- .github/workflows/ci.yaml
- .github/workflows/security.yaml
- contxt/cli/clients.py
- contxt/cli/commands/clusters.py
- contxt/cli/commands/edge_nodes.py
- contxt/cli/commands/project_envs.py
- contxt/cli/commands/projects.py
- contxt/cli/log.py
- contxt/cli/main.py
- contxt/cli/utils.py
- contxt/services/api.py
https://ndustrialio.atlassian.net/browse/CONTXT-1787
> feat: project crud

- contxt/cli/commands/project_envs.py
- contxt/cli/commands/projects.py
- contxt/cli/commands/service_instances.py
@jeffdyoung Let me know if we can get together and test this out.
> fix(cli): correct usability bugs

- contxt/services/events.py
Committed via https://github.com/asottile/all-repos
> fix: update events api url

- contxt/models/bus.py
- contxt/services/bus.py
* [JIRA](): To use this bus service as a dependency, we need to support custom environments on initialization of the class so we can hold those specific configurations outside of this repo
> feat: add ability to specify custom bus environments

- contxt/cli/commands/ems.py
- contxt/models/__init__.py
* [JIRA](https://ndustrialio.atlassian.net/browse/SUP-2617): CLI not working with new APIs
> Fix facilities requests

- contxt/auth/__init__.py
- poetry.lock
- pyproject.toml
- tests/auth/test_base.py
* [SUP-3069](https://ndustrialio.atlassian.net/browse/SUP-3069)
> chore: bump pyjwt version

- README.md
* [JIRA](): Background for changes
> fix: Attempt to make an actual release by adding space to README.md

- poetry.lock
* [CONTXT-9054](https://ndustrialio.atlassian.net/browse/CONTXT-9054)
[CONTXT-9054]: https://ndustrialio.atlassian.net/browse/CONTXT-9054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build(deps): Bump dep versions with vulnerability issues [CONTXT-9054]

- contxt/cli/commands/iot.py
- contxt/services/iot.py
* [CONTXT-10354 -- Provisioning Mode](https://ndustrialio.atlassian.net/browse/CONTXT-10354): Background for changes
> feat: provisioning mode

- contxt/cli/commands/edge_nodes.py
- contxt/cli/commands/service_instances.py
- contxt/models/contxt.py
- contxt/services/contxt.py
- contxt/services/contxt_deployments.py
* [JIRA](https://ndustrialio.atlassian.net/browse/SUP-15403): Contxt CLI question
> feat: add grant querying for edge nodes, service instances

- contxt/cli/clients.py
- contxt/cli/commands/edge_nodes.py
- contxt/cli/commands/roles.py
- contxt/cli/commands/service_instances.py
- contxt/services/__init__.py
- contxt/services/contxt_access.py
add requested functionality around service instance, role and edge node updates
* [JIRA](https://ndustrialio.atlassian.net/browse/SUP-15403): Contxt CLI question
Tested all changes locally
> SUP-15403-cli-updates

- contxt/cli/commands/roles.py
- contxt/cli/commands/service_instances.py
- contxt/models/contxt.py
- contxt/services/contxt_access.py
- contxt/services/contxt_deployments.py
* [JIRA](https://ndustrialio.atlassian.net/browse/SUP-15403): Contxt CLI Question
Tested locally in postman.
> add service instance scope commands to cli

- contxt/cli/clients.py
* [JIRA](https://ndustrialio.atlassian.net/browse/CONTXT-11686): Background for changes
> enable machine auth if client id/secret set
