contxt/__main__.py
contxt/auth/__init__.py
contxt/auth/cli.py
contxt/auth/machine.py
contxt/cli/parsers.py
contxt/legacy/auth/__init__.py
contxt/legacy/auth/cli.py
contxt/legacy/auth/machine.py
contxt/legacy/services/auth.py
contxt/services/api.py
contxt/services/assets.py
contxt/services/auth.py
contxt/services/bus.py
contxt/services/contxt.py
contxt/services/ems.py
contxt/services/events.py
contxt/services/facilities.py
contxt/services/iot.py
contxt/utils/__init__.py
setup.py
tests/integration/it.py
tests/integration/it_assets.py
tests/services/test_auth.py

* [Contxt SDK: Fix Auth issues](https://ndustrialio.atlassian.net/browse/CTOOLS-16)
* Create new `TokenProvider` class, whose sole responsibility is to provide a valid unexpired access token (contains the logic to update expired tokens)
* Update `ApiService` to accept new `TokenProvider` 
* Update `AuthService` to inherit from the more recent `ConfiguredApiService`
* Update `BaseAuth`, `MachineAuth`, and `CliAuth` to more clearly follow the flows defined below
* Auth flows
* Machine (simple case): `BaseAuth` (and `MachineAuth`) are instantiated with `client_id` and `client_secret`. To authenticate to a service, this class provides a method to simply return a `TokenProvider` for the specified audience.
* CLI (unique case): `CliAuth` requires a 2-step process. First, a Contxt …

CTOOLS-16: New Auth classes

---

contxt/__version__.py
contxt/models/assets.py

* `CompleteAsset` was erroneously inheriting from an `ABC` but not overloading the abstract methods, preventing instantiation

Remove inheritance from CompleteAsset

---

contxt/__version__.py
contxt/models/assets.py
contxt/services/assets.py

* [JIRA](https://lineagelogistics.atlassian.net/browse/NSIGHT-199): Syncing metric values had some bugs

Fix upserting metric values

---

contxt/services/api.py
contxt/services/assets.py
contxt/services/auth.py
contxt/services/bus.py
contxt/services/contxt.py
contxt/services/ems.py
contxt/services/events.py
contxt/services/facilities.py
contxt/services/iot.py
contxt/services/ngest.py
tests/integration/test_base_api.py

* Enable API retries on certain server errors

Add retry option to api

---

Makefile
contxt/models/iot.py
contxt/services/iot.py
tests/integration/test_iot_service.py

* Support for making batched requests to IOT API

Add support for IOT batch endpoint

---

CHANGELOG.md
Makefile
contxt/models/assets.py
contxt/models/bus.py
contxt/models/contxt.py
contxt/models/ems.py
contxt/models/events.py
contxt/models/facilities.py
contxt/models/health.py
contxt/models/iot.py
poetry.lock
pyproject.toml

* Reduce code duplication (from 3 dupes to 2) when defining a model
* A future PR will tackle the last duplication, which requires changing [de]serialization implementation
* Take advantage of nice `dataclass` features

Use dataclass for models

---

contxt/models/changetrackingrecord.py
tests/unit/test_ctr.py

* [JIRA](NA): ETL CLI upgrades for injecting CTRs into messaging channels begs the need for a serializable CTR object that can be instantiated and manipulated and dumped into json and put on a message que

Serializable CTR object for injecting CTR records into ETL channels

---

.github/workflows/release.yaml

https://github.com/marvinpinto/actions/issues/39 A spelling change broke the action because it was somehow changed without updating the version number. The repo owner suggests changing it to latest until he gets around to versioning it.

Updating the version to latest

---

contxt/models/events.py

The default should be None for creating

Defaulting ID to none for triggered events

---

contxt/cli/commands/iot.py
contxt/services/iot.py

* [JIRA](https://ndustrialio.atlassian.net/browse/CONTXT-1483): Background for changes
- Exposed endpoint through the CLI
Sample command:
`contxt iot delete-data-point --output-id 1939 --field-human-name power.demand --interval 900 --time 2020-08-04T03:00:00Z`

Exposing deletion endpoint through the CLI

---

contxt/cli/commands/ems.py
contxt/utils/serializer.py

* Dumping to csv assumed that the first row contained all columns present in every other row. Don't make that assumption

fix: ems export command

---

contxt/services/api.py
poetry.lock
tests/services/test_api.py

This adds backwards-compatible changes to handle the following [breaking change](https://github.com/urllib3/urllib3/issues/2092) from `urllib3`:
```
ValueError: Using both 'allowed_methods' and 'method_whitelist' together is not allowed. Instead only use 'allowed_methods'
```

fix(api): support breaking change in urllib3

---

contxt/cli/commands/auth.py

This adds a convenience command to get an access token for a certain audience (i.e. one of our API's). For example:
```sh
contxt auth token <audience>
```
This is useful when you want to make API requests yourself, outside of the sdk.

feat(cli): add token command

---

contxt/models/ems.py

* The `id` field is not longer being returned and is not necessary to make the call/response work.

Make id optional. No longer required

---

contxt/models/bus.py
contxt/services/api.py
contxt/services/bus.py

* Adding the ability in another CLI to create a message bus channel
* One of the endpoints in another CLI is calling an endpoint that does not return JSON, but instead an `application/jwt`

Feature: Add bus channel creation. Add raw post option

---

meta.yaml

* [CONTXT-2845](https://ndustrialio.atlassian.net/browse/CONTXT-2845): meta.yaml

CONTXT-2845 map project dependencies

---

contxt/services/contxt.py
contxt/services/contxt_deployments.py

* [CONTXT-2921](https://ndustrialio.atlassian.net/browse/CONTXT-2921): Background for changes

CONTXT-2921 correct staging endpoints

---

contxt/cli/commands/clusters.py
contxt/cli/commands/services.py

* Corrected a couple typos in the CLI help text to avoid confusion

corrected typos in CLI help

---

.github/workflows/ci.yaml

* Need a release 3.0.0 in order to get deprecation of assets_api into SDK for customers to use.
- Enable the release workflow.

Re-enable release builds

---

contxt/services/api.py

Handles the case where the _json_ representation of the error is just a string value

fix: Non-json error handling

---

contxt/services/api.py

* [CONTXT-3627](https://ndustrialio.atlassian.net/browse/CONTXT-3627): To identify requests made through the CLI more accurately.

feat: add user-agent HTTP header

---

contxt/cli/clients.py
contxt/services/ems.py
contxt/services/events.py
contxt/services/iot.py
contxt/services/ngest.py
contxt/services/nionic.py
contxt/utils/orgs.py

* [CONTXT-4194](https://ndustrialio.atlassian.net/browse/CONTXT-4194)
BREAKING CHANGE: `IotService`, `EventsService`, `NgestService`, and `SpecializedNgestService`
now require `org_id` to be instantiated. This is needed for hitting the tenant-specific APIs.
As such, these services, as well as `EmsService` now point to
https://$TENANT.$SERVICE.api.ndustrial.io.
[CONTXT-4194]: https://ndustrialio.atlassian.net/browse/CONTXT-4194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CONTXT-4194 switch to tenant urls

---

contxt/models/ems.py

* [JIRA](https://ndustrialio.atlassian.net/browse/SUP-3820): EMS API change broke SDK.

fix: Remove baseline from EMS model 

---

contxt/cli/commands/iot.py
contxt/models/iot.py
contxt/services/iot.py
poetry.lock
pyproject.toml

* When generating field groupings from csv, the group name was not properly slugified to match the lookup in the feeds API
* No automation existed for assigning field groupings to categories

Fix create field groupings

---

.github/workflows/ci.yaml
README.md
poetry.lock
pyproject.toml

* [CONTXT-4372](https://ndustrialio.atlassian.net/browse/CONTXT-4372): Python 3.7 goes EOL on the 27th of June 2023
[CONTXT-4372]: https://ndustrialio.atlassian.net/browse/CONTXT-4372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: deprecate Python 3.7

---

contxt/cli/commands/iot.py

- Field provisioning errors don't explain which field failed
- Add field descriptor to error message

fix: add field descriptor to provision failed log statement

---

contxt/services/bus.py

* [CONTXT-4543](https://ndustrialio.atlassian.net/browse/CONTXT-4543): Lineage wants a way to look at messages without affecting consumers
[CONTXT-4543]: https://ndustrialio.atlassian.net/browse/CONTXT-4543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: peek messages on a channel subscription

---

contxt/utils/orgs.py

* [SUP-4015](https://ndustrialio.atlassian.net/browse/SUP-4015): Failure provisioning LSC
[SUP-4015]: https://ndustrialio.atlassian.net/browse/SUP-4015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add newer org ID to slug mappings

---

.pre-commit-config.yaml
contxt/cli/commands/iot.py
contxt/cli/utils.py

feat: add required is_totalizer field to contxt field create command

---

contxt/cli/commands/service_instances.py

* [[JIRA](https://ndustrialio.atlassian.net/browse/CONTXT-8207)](): Don't prompt for Project Env when deploying unmanaged service-instances.
- Change from PROMPT to required=False

Don't prompt for project env if not provided

---

poetry.lock

* [CONTXT-9054](https://ndustrialio.atlassian.net/browse/CONTXT-9054)
[CONTXT-9054]: https://ndustrialio.atlassian.net/browse/CONTXT-9054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump setuptools version [CONTXT-9054]

---

.gitignore

* ignore the `.idea` development directory made by PyCharm

chore: ignore IDEA editor local dir

---

README.md
poetry.lock
pyproject.toml

- https://ndustrialio.atlassian.net/browse/CONTXT-9054
- formatter major version update
- force a PyPi release

build(deps): bump formatter major version [CONTXT-9054]

---

.github/workflows/ci.yaml

* [CONTXT-9166](https://ndustrialio.atlassian.net/browse/CONTXT-9166)
[CONTXT-9166]: https://ndustrialio.atlassian.net/browse/CONTXT-9166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add Python 3.12 to test matrix [CONTXT-9166]

---

poetry.lock
pyproject.toml

* Fixes https://github.com/ndustrialio/contxt-sdk-python/security/dependabot/35 
```
The current project's supported Python range (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
- cryptography requires Python !=3.9.0,!=3.9.1,>=3.7, so it will not be satisfied for Python 3.9 || 3.9.1
```

fix: bump Python patch version to accommodate crypto package

---

contxt/models/iot.py

* [JIRA CONTXT-10461](https://ndustrialio.atlassian.net/browse/CONTXT-10461): Background for changes

CONTXT-10461 - Allow is_totalizer to be set when creating fields

---

contxt/__init__.py

* [JIRA](https://ndustrialio.atlassian.net/browse/CONTXT-11468): contxt-sdk-python package update

switch to importlib for pulling distribution version info
